### ISSUE TITLE
invalid m3u file format. Expected #EXTM3U file header

### ISSUE THREAD

**Issue by rouissi-iheb** [pierre-emmanuelJ/iptv-proxy#123]
Hi , hope you all safe , 

Am trying to run the docker container with valid IPTV M3U file wich i did play on VLC media player but i always get this error : 

```
docker-compose up
Creating iptv-proxy ... done
Attaching to iptv-proxy
iptv-proxy    | 2022/04/22 20:23:44 invalid m3u file format. Expected #EXTM3U file header
```
this is my docker-compose.yml file : 

```
version: "3"
services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # If your are using local m3u file instead of m3u remote file
      # put your m3u file in this folder
      - ./iptv:/root/iptv
    container_name: "iptv-proxy"
    restart: on-failure
    ports:
       # have to be the same as ENV variable PORT
      - 8080:8080
    environment:
      # if you are using m3u remote file
      # M3U_URL: https://example.com/iptvfile.m3u
      M3U_URL: /root/iptv/iptv.m3u
      # Port to expose the IPTVs endpoints
      PORT: 8080
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: localhost
      GIN_MODE: release
      ## Xtream-code proxy configuration
      XTREAM_USER: xtream_user
      XTREAM_PASSWORD: xtream_password
      XTREAM_BASE_URL: "http://localhost:8080"
      ##### UNSAFE AUTH TODO ADD REAL AUTH
      #will be used for m3u and xtream auth poxy
      USER: test
      PASSWORD: test

```
i did create an iptv.m3u file inside iptv folder :
```
#EXTM3U
#EXTINF:-1,PREMIUM SPORT 1 HD
#EXTVLCOPT:http-user-agent=ricotv
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/1
#EXTINF:-1,BEIN SPORT PREMIUM 2
#EXTVLCOPT:http-user-agent=ricotv
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/249
#EXTINF:-1,PREMIUM SPORT 2 HD
#EXTVLCOPT:http-user-agent=ricotv
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/3
#EXTINF:-1,PREMIUM SPORT 3 HD
#EXTVLCOPT:http-user-agent=ricotv
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/5
```

Did not work for me since the fomrat was not the same as in README.md file so i used the same links of my working iptv file with the exemple format so my iptv.m3u file lokks like this now : 

```
#EXTM3U
#EXTINF:-1 tvg-ID="examplechanel1.com" tvg-name="chanel1" tvg-logo="http://ch.xyz/logo1.png" group-title="USA HD",CHANEL1-HD
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/1
#EXTINF:-1 tvg-ID="examplechanel2.com" tvg-name="chanel2" tvg-logo="http://ch.xyz/logo2.png" group-title="USA HD",CHANEL2-HD
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/1
#EXTINF:-1 tvg-ID="examplechanel3.com" tvg-name="chanel3" tvg-logo="http://ch.xyz/logo3.png" group-title="USA HD",CHANEL3-HD
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/1
#EXTINF:-1 tvg-ID="examplechanel4.com" tvg-name="chanel4" tvg-logo="http://ch.xyz/logo4.png" group-title="USA HD",CHANEL4-HD
http://xx.xyz:25461/jjhdfsffjjg/jjhdfsffjjg/1
```
but still showing the same issue.
Can anyone help me with that ? what i did wrong or what's missing ?
