### ISSUE TITLE
[BUG] URI provided for playlist with no tracks

### ISSUE THREAD

**Issue by CyberPoison** [pierre-emmanuelJ/iptv-proxy#46]
Hi everyone i getting some issue when running the docker container i get this message on the logs the m3u is correctly in the folder but looks like something is wrong

this is my logs

```
URI provided for playlist with no tracks
URI provided for playlist with no tracks
URI provided for playlist with no tracks
URI provided for playlist with no tracks
URI provided for playlist with no tracks
URI provided for playlist with no tracks
URI provided for playlist with no tracks
URI provided for playlist with no tracks
```

and this is my docker-compose up -d

```
version: "3"
services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # If your are using local m3u file instead of m3u remote file
      # put your m3u file in this folder
      - /root/Livetv:/root/iptv
    container_name: "iptv-proxy"
    restart: on-failure
    ports:
       # have to be the same as ENV variable PORT
      - 9593:9593
    environment:
      # if you are using m3u remote file
      # M3U_URL: https://example.com/iptvfile.m3u
      M3U_URL: /root/iptv/LiveTV.m3u
      # Port to expose the IPTVs endpoints
      PORT: 9593
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: localhost
      GIN_MODE: release
      ## Xtream-code proxy configuration
      ##### UNSAFE AUTH TODO ADD REAL AUTH
      #will be used for m3u and xtream auth poxy
      USER: Admin
      PASSWORD: test
```
